#!/usr/bin/env ansible-playbook

---

- hosts: local
  become: true
  tasks:
    - name: fetch jsquery
      git:
        repo: https://github.com/postgrespro/jsquery.git
        dest: /ansible/tmp/jsquery
        clone: true
    - name: build jsquery
      make:
        chdir: /ansible/tmp/jsquery
        params:
          USE_PGXS: 1
    - name: install jsquery locally
      make:
        chdir: /ansible/tmp/jsquery
        target: install
        params:
          USE_PGXS: 1
    - name: copy jsquery lib for pg
      shell: cp /usr/lib/postgresql/9.5/lib/jsquery.so /ansible/art/pg/lib
    - name: copy jsquery header for pg
      shell: cp /usr/include/postgresql/9.5/server/jsquery.h /ansible/art/pg/header
    - name: copy jsquery sql A for pg
      shell: cp /usr/share/postgresql/9.5/extension/jsquery--1.0--1.1.sql /ansible/art/pg/extension
    - name: copy jsquery sql B for pg
      shell: cp /usr/share/postgresql/9.5/extension/jsquery--1.1.sql /ansible/art/pg/extension
    - name: copy jsquery extension into pg docker
      shell: cp /usr/share/postgresql/9.5/extension/jsquery.control /ansible/art/pg/extension
    - name: install jsquery extention in pg
      postgresql_query:
        login_host: 127.0.0.1
        login_user: '{{ lookup("env", "IPL_DEV_DEPLOY_PG_USER") }}'
        login_password: '{{ lookup("env", "IPL_DEV_DEPLOY_PG_PASSWORD") }}'
        port: 5432
        db: postgres
        query: CREATE EXTENSION IF NOT EXISTS jsquery;
    # - name: create api db
    #   postgresql_db:
    #     name: api
    #     login_host: 127.0.0.1
    #     login_password: qweasdzxc
    # - name: Ensure .ssh
    #   file:
    #     dest: "{{ GITLAB_KEY_PATH_DEST | dirname }}"
    #     mode: 0700
    #     owner: vagrant
    #     state: directory
    # - name: Provide with git config
    #   template:
    #     src: "../templates/config.ssh.j2"
    #     dest: "/home/vagrant/.ssh/config"
    #     mode: 0600
    #     owner: vagrant
    # - name: Provide with gitlab key
    #   copy:
    #     src: "{{GITLAB_KEY_PATH}}_en"
    #     dest: "{{ GITLAB_KEY_PATH_DEST }}"
    #     mode: 0600
    #     owner: vagrant
    # - name: Clone api db migrations
    #   git:
    #     repo: git@gitlab.app.ipl:db/api.git
    #     dest: /home/vagrant/migrations/api
    #     clone: yes
    #     accept_hostkey: yes
    # - name: Apply migrations
    #   shell: |
    #     ipmt up
    #   args:
    #     chdir: /home/vagrant/migrations/api
    #   environment:
    #     IPMT_DSN: postgres:qweasdzxc@localhost:5432/api
    # - name: Apply fixtures
    #   shell: |
    #     pg_restore -h localhost -U postgres -d api /vagrant/files/fixtures_api.dump 
    #   environment:
    #     PGPASSWORD: qweasdzxc
