#!/usr/bin/env ansible-playbook
# up.pg_struct_n_data.yml
# заботится о создании структуры необходимых баз и наполнении их фикстурами

---


- hosts: local
  become: true
  gather_facts: false
  vars:
    # чтобы лукапами не повторяться
    GITLAB_URL: "{{ lookup('env', 'IPL_DEV_DEPLOY_GITLAB_URL') }}"
    GITLAB_PATH_API: "{{ lookup('env', 'IPL_DEV_DEPLOY_GITLAB_PATH_API') }}"
    PG_USER: "{{ lookup('env', 'IPL_DEV_DEPLOY_PG_USER') }}"
    PG_PASSWORD: "{{ lookup('env', 'IPL_DEV_DEPLOY_PG_PASSWORD') }}"
  tasks:
    # заливает заботливо подготовленные тестовые данные
    - name: Apply fixtures
      shell: "pg_restore -h ipl_dev_deploy_pg -U {{ PG_USER }} -d api /ansible/art/files/fixtures_api.dump"
      environment:
        PGPASSWORD: "{{ PG_PASSWORD }}"
