#!/usr/bin/env ansible-playbook

---


- hosts: local
  become: true
  gather_facts: false
  vars:
    GITLAB_URL: "{{ lookup('env', 'IPL_DEV_DEPLOY_GITLAB_URL') }}"
    GITLAB_PATH_API: "{{ lookup('env', 'IPL_DEV_DEPLOY_GITLAB_PATH_API') }}"
    PG_USER: "{{ lookup('env', 'IPL_DEV_DEPLOY_PG_USER') }}"
    PG_PASSWORD: "{{ lookup('env', 'IPL_DEV_DEPLOY_PG_PASSWORD') }}"
  tasks:
    - name: fetch jsquery
      git:
        repo: https://github.com/postgrespro/jsquery.git
        dest: /ansible/tmp/jsquery
        clone: true
    - name: build jsquery
      make:
        chdir: /ansible/tmp/jsquery
        params:
          USE_PGXS: 1
    - name: install jsquery locally
      make:
        chdir: /ansible/tmp/jsquery
        target: install
        params:
          USE_PGXS: 1
    - name: copy jsquery lib for pg
      shell: cp /usr/lib/postgresql/9.5/lib/jsquery.so /ansible/pg_tmp/lib
    - name: copy jsquery header for pg
      shell: cp /usr/include/postgresql/9.5/server/jsquery.h /ansible/pg_tmp/header
    - name: copy jsquery sql A for pg
      shell: cp /usr/share/postgresql/9.5/extension/jsquery--1.0--1.1.sql /ansible/pg_tmp/extension
    - name: copy jsquery sql B for pg
      shell: cp /usr/share/postgresql/9.5/extension/jsquery--1.1.sql /ansible/pg_tmp/extension
    - name: copy jsquery extension into pg docker
      shell: cp /usr/share/postgresql/9.5/extension/jsquery.control /ansible/pg_tmp/extension
    - name: install jsquery extention in pg
      postgresql_query:
        login_host: ipl_dev_deploy_pg
        login_user: '{{ PG_USER }}'
        login_password: '{{ PG_PASSWORD }}'
        port: 5432
        db: postgres
        query: CREATE EXTENSION IF NOT EXISTS jsquery;
