#!/usr/bin/env bash
set +x

echo $(pwd)
. /ansible/box/env.sh

socat tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock &
ssh-keygen -yf /ansible/pk > ~/.ssh/authorized_keys

echo Run "up" book...
ansible-playbook /ansible/art/playbooks/up.yml
/usr/sbin/sshd -D