#!/usr/bin/env bash
set +x

if [ ! -t 1 ] ; then
  echo "No tty available."
  exit 0
fi

echo "$@"
echo $(pwd)
. /ansible/box/env.sh

socat tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock &
if test -f /ansible/art/playbooks/"$1".yml;
then
	echo Run book...
	ansible-playbook /ansible/art/playbooks/"$1".yml
else
	echo Run command...
	exec "$@"
fi
