#!/usr/bin/env bash
set +x

socat tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock &
if test -f playbooks/"$1".yml;
then
	echo Run book...
	ansible-playbook playbooks/"$1".yml
else
	echo Run command...
	exec "$@"
fi
